import { Link } from "react-router-dom";
import { ShieldCheck } from "lucide-react";
import {
  TrustCapabilities,
  TrustGatewayCard,
  TrustScopeNote,
} from "@/components/verification/CapimaxTrustGateway";

/**
 * Verification Center — a GATEWAY page (no verification logic lives here). Every document,
 * certificate and record issued by this platform (or by external parties: valuers, insurers,
 * legal advisors, auditors, financial institutions, government authorities) is verified,
 * status-checked and downloaded through the CENTRAL Capimax Trust platform. This page simply
 * explains that and hands the user off to Capimax Trust. (Group-wide requirement — the same
 * page exists on every Capimax platform; each one links to the single Capimax Trust source.)
 */

export default function VerificationCenter() {
  return (
    <div className="min-h-screen bg-background">
      {/* Hero — large platform logo + title + intro */}
      <section className="bg-gradient-to-br from-primary/10 via-background to-secondary/10 py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center">
            <img
              src="/capimax-logo.png"
              alt="Capimax PropShare"
              className="mx-auto h-16 md:h-20 w-auto mb-8"
            />
            <div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/5 px-4 py-1.5 text-sm font-medium text-primary mb-5">
              <ShieldCheck className="h-4 w-4" /> Verification Center
            </div>
            <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-6">
              Verify documents through Capimax Trust
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground leading-relaxed">
              All documents, certificates, and records issued through this platform—including those
              generated by the Capimax ecosystem as well as documents issued by external
              organizations such as valuation firms, insurance providers, legal advisors, auditors,
              financial institutions, and government authorities—can be verified, their status
              reviewed, and official copies downloaded through the Capimax Trust platform.
            </p>
            <p className="mt-5 text-base md:text-lg text-muted-foreground leading-relaxed">
              Capimax Trust serves as the central verification gateway for the Capimax ecosystem,
              providing a secure and trusted source for validating the authenticity and integrity of
              registered documents.
            </p>
          </div>
        </div>
      </section>

      <div className="container mx-auto px-4 py-14 max-w-4xl space-y-12">
        {/* Capimax Trust gateway card + primary CTA (shared with the dashboard tab) */}
        <TrustGatewayCard />

        <TrustCapabilities />

        {/* Honest scope note — verification never happens on this platform */}
        <TrustScopeNote />

        <div className="text-center">
          <Link to="/" className="text-sm text-muted-foreground hover:text-foreground underline underline-offset-4">
            Back to home
          </Link>
        </div>
      </div>
    </div>
  );
}
