import { Link } from "react-router-dom";
import { ShieldCheck, ExternalLink, FileCheck2, ListChecks, Download, ScrollText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

/**
 * Verification Center — a GATEWAY page (no verification logic lives here). Every document,
 * certificate and record issued by this platform (or by external parties: valuers, insurers,
 * legal advisors, auditors, financial institutions, government authorities) is verified,
 * status-checked and downloaded through the CENTRAL Capimax Trust platform. This page simply
 * explains that and hands the user off to Capimax Trust. (Group-wide requirement — the same
 * page exists on every Capimax platform; each one links to the single Capimax Trust source.)
 */

// The central Capimax Trust verification gateway. Single source of truth for the destination.
const CAPIMAX_TRUST_URL = "https://www.capimax.pro";

const CAPABILITIES = [
  { icon: FileCheck2, title: "Verify authenticity", text: "Confirm that a document or certificate is genuine and was officially issued." },
  { icon: ListChecks, title: "Review status", text: "See the current status of any registered document or record." },
  { icon: Download, title: "Download the official copy", text: "Obtain the authoritative, official version of the document." },
  { icon: ScrollText, title: "View verification data", text: "Inspect the verification details attached to each document." },
];

export default function VerificationCenter() {
  return (
    <div className="min-h-screen bg-background">
      {/* Hero — large platform logo + title + intro */}
      <section className="bg-gradient-to-br from-primary/10 via-background to-secondary/10 py-16 md:py-24">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center">
            <img
              src="/capimax-logo.png"
              alt="Capimax PropShare"
              className="mx-auto h-16 md:h-20 w-auto mb-8"
            />
            <div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/5 px-4 py-1.5 text-sm font-medium text-primary mb-5">
              <ShieldCheck className="h-4 w-4" /> Verification Center
            </div>
            <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-6">
              Verify documents through Capimax Trust
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground leading-relaxed">
              All documents, certificates, and records issued through this platform—including those
              generated by the Capimax ecosystem as well as documents issued by external
              organizations such as valuation firms, insurance providers, legal advisors, auditors,
              financial institutions, and government authorities—can be verified, their status
              reviewed, and official copies downloaded through the Capimax Trust platform.
            </p>
            <p className="mt-5 text-base md:text-lg text-muted-foreground leading-relaxed">
              Capimax Trust serves as the central verification gateway for the Capimax ecosystem,
              providing a secure and trusted source for validating the authenticity and integrity of
              registered documents.
            </p>
          </div>
        </div>
      </section>

      <div className="container mx-auto px-4 py-14 max-w-4xl space-y-12">
        {/* Capimax Trust gateway card + primary CTA */}
        <Card className="border-primary/20 overflow-hidden">
          <div className="bg-gradient-to-br from-primary/10 to-transparent p-8 md:p-12 text-center">
            {/* Official Capimax Trust logo on a clean white plate (the artwork has a light ground). */}
            <div className="mx-auto mb-6 inline-flex items-center justify-center rounded-2xl bg-white p-6 shadow-sm ring-1 ring-border">
              <img
                src="/capimax-trust-logo.png"
                alt="Capimax Trust — Verified · Secured · Connected"
                className="h-24 md:h-28 w-auto"
              />
            </div>
            <h2 className="sr-only">Capimax Trust</h2>
            <p className="mt-1 text-sm font-medium tracking-wide text-primary uppercase">
              Central Verification Gateway
            </p>
            <p className="mx-auto mt-4 max-w-xl text-muted-foreground">
              Continue to Capimax Trust to verify a document, review its status, and download the
              official copy.
            </p>
            <div className="mt-7">
              <Button asChild size="lg" className="gap-2 text-base">
                <a href={CAPIMAX_TRUST_URL} target="_blank" rel="noopener noreferrer">
                  Go to Capimax Trust <ExternalLink className="h-4 w-4" />
                </a>
              </Button>
            </div>
            <a
              href={CAPIMAX_TRUST_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="mt-4 inline-block text-sm text-primary underline underline-offset-4 hover:text-primary/80"
            >
              www.capimax.pro
            </a>
          </div>
        </Card>

        {/* What you can do on Capimax Trust */}
        <div>
          <h3 className="text-center text-xl font-semibold text-foreground mb-6">
            On Capimax Trust you can
          </h3>
          <div className="grid gap-4 sm:grid-cols-2">
            {CAPABILITIES.map((c) => (
              <Card key={c.title}>
                <CardContent className="flex items-start gap-4 p-5">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10">
                    <c.icon className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <div className="font-semibold text-foreground">{c.title}</div>
                    <p className="mt-1 text-sm text-muted-foreground">{c.text}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Honest scope note — verification never happens on this platform */}
        <p className="text-center text-sm text-muted-foreground max-w-2xl mx-auto">
          To keep verification consistent and trustworthy across the group, all document
          verification for the Capimax ecosystem is handled exclusively by Capimax Trust. This page
          is a secure gateway to that central service.
        </p>

        <div className="text-center">
          <Link to="/" className="text-sm text-muted-foreground hover:text-foreground underline underline-offset-4">
            Back to home
          </Link>
        </div>
      </div>
    </div>
  );
}
